#  _  ___ _   _         
# | |/ (_) |_| |_ _   _ 
# | ' /| | __| __| | | |
# | . \| | |_| |_| |_| |
# _|\_\_|\__|\__|\__, |
#                |___/ 
# --------------------------------------------
#
# By notrealekansh

# Font
font_family JetBrainsMono Nerd Font
font_size 11.5

# Cursor
cursor_shape beam
cursor_blink_interval 0

# Padding
window_padding_width 12

# Transparency (works great with Hyprland blur)
background_opacity 0.4

# Colors (Catppuccin-ish)
background #0e0e12
foreground #cdd6f4

selection_background #313244
selection_foreground #cdd6f4

# Performance
enable_audio_bell no
repaint_delay 10
input_delay 3
5
