# Hyprpaper configuration

ipc = on
splash = false

# Default wallpaper block for all monitors
wallpaper {
    monitor =
    path = /home/notrealekansh/.config/hypr/hyprpaper/flowering-rain.png
    fit_mode = cover
}

