
#  _   _                  _            _    
# | | | |_   _ _ __  _ __| | ___   ___| | __
# | |_| | | | | '_ \| '__| |/ _ \ / __| |/ /
# |  _  | |_| | |_) | |  | | (_) | (__|   < 
# |_| |_|\__, | .__/|_|  |_|\___/ \___|_|\_\
#        |___/|_|
#  
# ----------------------------------------------------- 
# Full documentation https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock


source=~/.config/hypr/hyprlock/colors.conf

background {
    monitor =
    path = ~/Pictures/wallpapers/main.jpg
    color = rgba(25, 20, 20, 1.0)

    blur_passes = 3 # 0 disables blurring
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8916
}

input-field {
    monitor =

    size = 260, 48

    outline_thickness = 0

    outer_color = rgba(0,0,0,0)
    inner_color = rgba(20,20,20,0.45)

    font_color = rgb(255,255,255)

    rounding = 16

    fade_on_empty = false

    placeholder_text = Enter your passphrase
    fail_text = Authentication failed

    position = 0, -140
    halign = center
    valign = center
}

label {
    monitor =
    text = $LAYOUT
    color = $text_color
    font_size = 14
    font_family = $font_family
    position = -30, 30
    halign = right
    valign = bottom
}

label { # Caps Lock Warning
    monitor =
    text = cmd[update:250] ${XDG_CONFIG_HOME:-$HOME/.config}/hypr/scripts/check-capslock.sh
    color = $text_color
    font_size = 13
    font_family = $font_family
    position = 0, -200
    halign = center
    valign = center
}


label {
    monitor =
    text = $TIME
    color = $text_color

    font_size = 128
    font_family = $font_family_clock

    position = 0, 320
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:5000] date +"%A, %B %d"
    color = $text_color

    font_size = 32
    font_family = $font_family_clock

    position = 0, 220
    halign = center
    valign = center
}

image {
    monitor =
    path = 

    size = 110
    rounding = -1

    position = 0, 20
    halign = center
    valign = center
}

label {
    monitor =
    text = notrealekansh

    color = $text_color
    font_size = 24

    position = 0, -80
    halign = center
    valign = center
}

label { # Status
    monitor =
    text = cmd[update:5000] ${XDG_CONFIG_HOME:-$HOME/.config}/hypr/scripts/status.sh
    color = $text_color
    font_size = 14
    font_family = $font_family

    position = 30, -30
    halign = left
    valign = top
}

label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/script/notifications.sh

    color = rgba(255,255,255,0.7)
    font_size = 15

    position = 0, -430

    halign = center
    valign = center
}
