# Hyprpaper configuration

ipc = on
splash = false

# Default wallpaper block for all monitors
wallpaper {
    monitor =
    path = /home/notrealekansh/Pictures/wallpapers/Mountain Sea.jpg
    fit_mode = cover
}

